version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    ports:
      - "8000:8000"  # 映射端口
    volumes:
      - ./proxies.txt:/app/proxies.txt  # 挂载代理文件
      - ./getgrassDesktopBot.py:/app/getgrassDesktopBot.py  # 挂载Python脚本
    restart: unless-stopped
