version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    ports:
      - "8000:8000"  # 将容器的8000端口映射到服务器的8000端口
    volumes:
      - ./proxies.txt:/app/proxies.txt  # 挂载代理文件
    restart: unless-stopped
