version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app_container
    ports:
      - "8000:8000"
    volumes:
      - ./proxies.txt:/mnt/data/proxies.txt
    restart: unless-stopped
